# Generated by Django 4.1.7 on 2023-04-10 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=500)),
                ('telefone', models.CharField(max_length=20)),
                ('dataNascimento', models.DateField()),
            ],
        ),
    ]
