# Generated by Django 4.2.5 on 2023-09-11 11:24

import SegundaAtividade.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Minimo de 2 digitos.'), django.core.validators.MaxLengthValidator(50, 'Maximo de 50 digitos.')])),
                ('descricao', models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(10, 'Minimo de 10 digitos.'), django.core.validators.MaxLengthValidator(500, 'Maximo de 50 digitos.')])),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Minimo de 2 digitos.'), django.core.validators.MaxLengthValidator(100, 'Maximo de 100 digitos.')])),
                ('email', models.EmailField(max_length=1000, unique=True)),
                ('dataNascimento', models.DateField(validators=[SegundaAtividade.validators.data_menor_atual])),
                ('telefone', models.CharField(max_length=15, validators=[SegundaAtividade.validators.numero('Telefone'), django.core.validators.MinLengthValidator(8, 'Minimo de 8 digitos.'), django.core.validators.MaxLengthValidator(15, 'Maximo de 15 digitos.')])),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Minimo de 2 digitos.'), django.core.validators.MaxLengthValidator(100, 'Maximo de 100 digitos.')])),
                ('endereco', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True, validators=[django.core.validators.MinLengthValidator(5, 'Minimo de 5 digitos.'), django.core.validators.MaxLengthValidator(200, 'Maximo de 200 digitos.')])),
                ('telefone', models.CharField(max_length=15, validators=[SegundaAtividade.validators.numero('Telefone'), django.core.validators.MinLengthValidator(8, 'Minimo de 8 digitos.'), django.core.validators.MaxLengthValidator(15, 'Maximo de 100 digitos.')])),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Minimo de 2 digitos.'), django.core.validators.MaxLengthValidator(100, 'Maximo de 100 digitos.')])),
                ('cargo', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2, 'Minimo de 2 digitos.'), django.core.validators.MaxLengthValidator(50, 'Maximo de 50 digitos.')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=15, validators=[SegundaAtividade.validators.numero('Telefone'), django.core.validators.MinLengthValidator(8, 'Minimo de 8 digitos.'), django.core.validators.MaxLengthValidator(15, 'Maximo de 50 digitos.')])),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Minimo de 2 digitos.'), django.core.validators.MaxLengthValidator(100, 'Maximo de 100 digitos.')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8, 'Minimo de 2 digitos.'), django.core.validators.MaxLengthValidator(50, 'Maximo de 100 digitos.')])),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(2, 'Minimo de 2 digitos.'), django.core.validators.MaxLengthValidator(100, 'Maximo de 100 digitos.')])),
                ('descricao', models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(10, 'Minimo de 10 digitos.'), django.core.validators.MaxLengthValidator(500, 'Maximo de 100 digitos.')])),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'De graça não né.')])),
                ('estoque', models.IntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(0, 'Estoque vazio?.')])),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='produtos', to='SegundaAtividade.categoria')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='produtos', to='SegundaAtividade.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPedido', models.DateField(blank=True, null=True)),
                ('dataEntregaPrevista', models.DateField()),
                ('dataEntregaReal', models.DateField(blank=True, null=True, validators=[SegundaAtividade.validators.data_menor_igual_atual])),
                ('status', models.CharField(max_length=20, validators=[SegundaAtividade.validators.EscolhaValidator(['Em aberto', 'Em andamento', 'Finalizado'])])),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, '0???.')])),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos', to='SegundaAtividade.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoPagamento', models.CharField(max_length=50, validators=[SegundaAtividade.validators.EscolhaValidator(['Cartão de crédito', 'Boleto', 'Transferência bancária'])])),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'Valor deve ser maior que 0.')])),
                ('dataPagamento', models.DateField(validators=[SegundaAtividade.validators.data_menor_atual])),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SegundaAtividade.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='ItensPedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itensPedidos', to='SegundaAtividade.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos', to='SegundaAtividade.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2, 'Minimo de 2 digitos.'), django.core.validators.MaxLengthValidator(100, 'Maximo de 100 digitos.')])),
                ('numero', models.CharField(max_length=10, validators=[SegundaAtividade.validators.numero('Número'), django.core.validators.MaxLengthValidator(10, 'Maximo de 10 digitos.')])),
                ('complemento', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Minimo de 2 digitos.'), django.core.validators.MaxLengthValidator(50, 'Maximo de 50 digitos.')])),
                ('cidade', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(2, 'Minimo de 2 digitos.'), django.core.validators.MaxLengthValidator(50, 'Maximo de 50 digitos.')])),
                ('estado', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2, 'Exatamente 2 digitos.')])),
                ('cep', models.CharField(max_length=8, validators=[SegundaAtividade.validators.numero('Cep'), django.core.validators.MinLengthValidator(8, 'Exatamente 8 digitos.')])),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='SegundaAtividade.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.IntegerField()),
                ('quantidade', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, 'Nenhum item kkk?.')])),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01, 'Dea graça não né.')])),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras', to='SegundaAtividade.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to='SegundaAtividade.usuario'),
        ),
    ]
