# Generated by Django 4.1.7 on 2023-04-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SegundaAtividade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=32)),
                ('estoque', models.IntegerField()),
                ('descricao', models.CharField(max_length=2500)),
                ('imagem', models.BinaryField()),
            ],
        ),
    ]
