# Generated by Django 4.2.5 on 2023-09-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SegundaAtividade', '0002_rename_comprador_compra_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='dataCompra',
            field=models.DateField(),
        ),
    ]
