# Generated by Django 4.1.7 on 2023-04-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SegundaAtividade', '0002_produto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataPedido', models.DateField()),
                ('dataEntregaPrevista', models.DateField()),
                ('dataEntregaReal', models.DateField()),
                ('status', models.CharField(max_length=30)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.BinaryField(max_length=5000),
        ),
    ]
