# Generated by Django 4.1.7 on 2023-04-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SegundaAtividade', '0003_pedido_alter_produto_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='dataEntregaReal',
            field=models.DateField(blank=True),
        ),
    ]
