# Generated by Django 4.2.4 on 2023-08-21 13:52

from django.db import migrations
from SegundaAtividade.models import Usuario

def criar_root(apps, schema):
        Usuario.objects.create_user(username="root",password='root',email='root@localhost')

class Migration(migrations.Migration):

    dependencies = [
        ('SegundaAtividade', '0014_compra_cliente_pedido_funcionario'),
    ]

    operations = [
        migrations.RunPython(criar_root)
    ]
    
    